services:

  backend:
    image: ${BACKEND_IMAGE:-aura9931/grocecart-backend:latest}
    container_name: grocerycart-backend
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE:-aura9931/grocecart-frontend:latest}
    container_name: grocerycart-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
